### ISSUE TITLE
Error HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by ZdenekM** [luke142367/Docker-Lint-Action#13]
Any idea why I'm getting this?

```
2020-09-30T08:02:04.4619282Z ##[group]Run luke142367/Docker-Lint-Action@v1.1.1
2020-09-30T08:02:04.4619695Z with:
2020-09-30T08:02:04.4619977Z   target: docker/Dockerfile-*
2020-09-30T08:02:04.4620248Z env:
2020-09-30T08:02:04.4621272Z   GITHUB_TOKEN: ***
2020-09-30T08:02:04.4621519Z ##[endgroup]
2020-09-30T08:02:04.4652538Z ##[command]/usr/bin/docker run --name aac2aab726ce5aa9da47fe923b70b53374372b_888938 --label aac2aa --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_TARGET -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/arcor2/arcor2":"/github/workspace" aac2aa:b726ce5aa9da47fe923b70b53374372b
2020-09-30T08:02:05.2247762Z Error HttpError: Resource not accessible by integration
2020-09-30T08:02:05.2249254Z     at response.text.then.message (/.docker-lint-action/node_modules/@octokit/request/dist-node/index.js:66:23)
2020-09-30T08:02:05.2250159Z     at processTicksAndRejections (internal/process/task_queues.js:86:5)
2020-09-30T08:02:05.2282012Z Dockerfile Lint failed
```

**Comment by leosuncin** [comment]
This happen due a change in [GitHub Actions: Workflows triggered by Dependabot PRs will run with read-only permissions](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/)

**Comment by leosuncin** [comment]
A temporal fix will be:

```yaml
uses: luke142367/Docker-Lint-Action@v1.1.1
if: true && !contains(github.actor, 'dependabot')
with:
  target: Dockerfile
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This will skip the step if the action is started by dependabot

**Comment by kdpuvvadi** [comment]
Still same error.

**Comment by ccamel** [comment]
Any progress ? Is there a better solution than skiping the action for `dependabot` PRs?

Thx!

**Comment by TomerFi** [comment]
I don't think it related to `dependabot` itself, but more like to the fact of the pr source being a fork.
I have the same issue with this action on a pr someone (not `dependabot`, or a bot) opened in one of my projects, from his fork.
