### ISSUE TITLE
Docker lint fail

### ISSUE THREAD

**Issue by andridzi** [luke142367/Docker-Lint-Action#3]
Hi
I'm trying to use you action
But receiving next error
```
Error Error: Received status code 403
    at IncomingMessage.res.on (/.docker-lint-action/src/request.js:12:23)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
{"message":"You must authenticate via a GitHub App.","documentation_url":"https://developer.github.com/v3/checks/runs/#create-a-check-run"}
Dockerfile Lint failed
```

Could you please help?
Thanks

**Comment by luke142367** [comment]
Hi Andridzi,

Please can you try the latest version of the action v1.0.1 and let me know if the problem persists

**Comment by andridzi** [comment]
hi @luke142367 

The problem still persists

```Run luke142367/Docker-Lint-Action@v1.0.1
/usr/bin/docker run --name dfb7a2afcece24e43b884fe31d5a602fd4a_c412cf --label 488dfb --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_TARGET -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/test-actions/test-actions":"/github/workspace" 488dfb:7a2afcece24e43b884fe31d5a602fd4a
Error HttpError: You must authenticate via a GitHub App.
    at response.text.then.message (/.docker-lint-action/node_modules/@octokit/request/dist-node/index.js:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
Dockerfile Lint failed
##[error]Docker run failed with exit code 1```

May be I'm doing smth wrong... What kind of GITHUB_TOKEN needed?
I'm using the one I got from Settings --> Developer Settings --> Personal access tokens

**Comment by luke142367** [comment]
Ah yeah that is likely the issue, if you leave the `GITHUB_TOKEN` argument as 
`${{ secrets.GITHUB_TOKEN }}` it should work as this secret is set by default. You don't need to set your own secret

**Comment by andridzi** [comment]
it works!
thanks a lot for your help!
